net/nfp: fix build when debug enabled
build error:
.../drivers/net/nfp/nfp_net.c:1497:8: error:
‘dev_data’ undeclared (first use in this function); did you mean
‘dev_t’?
        dev_data->port_id);
	        ^

Fixes: 7ccf1115f0ab ("net/nfp: fix jumbo settings")
Cc: stable@dpdk.org

Signed-off-by: Ferruh Yigit <ferruh.yigit@intel.com>